[build]
  publish = "."
  functions = "netlify/functions"
  node_bundler = "esbuild"

  [functions]
  # Aquí defines módulos que no serán empaquetados por esbuild
  external_node_modules = ["node-fetch"]
